### PR TITLE
chore: check PR conventional commit name

### PR DESCRIPTION
**Pull request by rokam**
## Summary by CodeRabbit

- **Chores**
  - Introduced a GitHub Actions workflow to validate pull request titles.
  - Added a commit linting job to the existing Python build workflow.

### CODE REVIEW

**Comment by chemelli74** [comment]
I would suggest going with commlint.
Ex: https://github.com/chemelli74/aiocomelit/blob/main/.github/workflows/ci.yml#L27-L36

**Comment by rokam** [comment]
> I would suggest going with commlint. Ex: https://github.com/chemelli74/aiocomelit/blob/main/.github/workflows/ci.yml#L27-L36

Sure is useful, but I wan´t to check if the PR name is correct, commitlint checks the commits inside the PR.

**Comment by chemelli74** [comment]
> > I would suggest going with commlint. Ex: https://github.com/chemelli74/aiocomelit/blob/main/.github/workflows/ci.yml#L27-L36
> 
> Sure is useful, but I wan´t to check if the PR name is correct, commitlint checks the commits inside the PR. And, if we use squash, those commits are irrelevant.

Not exactly, commlint check that the PR commit is compliant to a schema. Like you are trying to achive with another hook.
If you name the PR wrongly, it won't pass. You can easily make a test if you prefer to double check.

**Comment by rokam** [comment]
I did both, one action just for PR name and a lint in the ci job.

**Review by chemelli74 — APPROVED** [review]

**Pull request merged**
