### PR TITLE
fix: protocol check in B6 devices

### PR DESCRIPTION
**Pull request by chemelli74**

### CODE REVIEW

**Comment by rokam** [comment]
Why change it without an issue related?

**Comment by chemelli74** [comment]
> Why change it without an issue related?

This is the only device with a check and IMHO was based on a "device" logic not a message one

**Comment by rokam** [comment]
> > Why change it without an issue related?
> 
> This is the only device with a check and IMHO was based on a "device" logic not a message one

We shouldn't change it without any related issues. We might create issues and we need stability.

**Comment by chemelli74** [comment]
Anyway we need to find a proper way to handle.
I'm 99% sure that it was a mistake ; is the only device with a if on the protocol.

If we don't change the logic, we need to introduce a constant for message protocol value(s)

**Comment by rokam** [comment]
Or just skip that line.

**Comment by chemelli74** [comment]
Nope, we will have doubts in future

**Review by wuwentao — APPROVED** [review]

**Pull request merged**
