### PR TITLE
fix(device)!: socket exception and process rebuild

### LINKED ISSUE #290: Cannot connect
### HA core version

2024.2.2

### Current integration version

0.5.5

### Last known working integration version

0.5.3

### Device type and model

Dehumidifier 00000Q1A (161)

### Working mobile app

Home Assisstant

### The description of problem

When unpowering the dehumidifier (e.g. by a switching plug), the connection to HA is lost and will not reconnect, when power is established again.

### The logs

[homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability
problems, be sure to disable it if you experience issues with Home Assistant
2024-08-11 06:30:27.100 ERROR (Luftentfeuchter) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 515, in run
    raise CannotConnect
midealocal.exceptions.CannotConnect

[https://api.github.com/repos/wuwentao/midea_ac_lan/issues/276]

### PR DESCRIPTION
**Pull request by wuwentao**
changes list:
1. process all the socket send/recv in try/except to prevent socket error
2. always close socket after exception matched and force reconnect to refresh
3. increase query timeout from 1 to 2, and only apply it to query cmd/msg
4. recovery socket timeout after query and recv socket msg done in each for loop.
5. rebuild process to remove the duplicate message parse.
6. rename some func and args
7. with current changes, I don't see any timeout exception in my local device testing, if there is any new error exist, we can continue improve it in future PRs.

Fixes #290 

## Summary by CodeRabbit

- **New Features**
	- Enhanced error handling for device discovery, now reporting `NoSupportedProtocol` for unsupported devices.
	- Streamlined socket connection process, improving reliability and clarity in communication.
	- Introduced `MessageResult` enumeration for improved clarity in message parsing.

- **Bug Fixes**
	- Updated tests to reflect changes in exception handling, ensuring accurate responses to device compatibility issues.

### CODE REVIEW

**Review by rokam — CHANGES_REQUESTED** [review]
@wuwentao this is a breaking change. It looks good. Can you please add tests to cover the changed code?

**Comment by wuwentao** [comment]
> @wuwentao this is a breaking change. It looks good. Can you please add tests to cover the changed code?

thanks for your review, but I don't thinks it's a good idea to add test now, most of the process is not fullly test and verified, we still need to improve and update it, once it stable, we can start to add test for it.

**Comment by wuwentao** [comment]
in addition, I don't think it can cover all, current process  should not match the finally version, it just focus on fix the socket exception  and some duplicate process rebuild, just to match the changes, especially for query socket timeout set and recovery.

I just found some new bug and push a new commit now, we may have new bug and issue with it, anyway, we can continue improve it and try to make it stable.

**Comment by rokam** [comment]
> and push a new commit now, we may



> in addition, I don't think it can cover all, current process should not match the finally version, it just focus on fix the socket exception and some duplicate process rebuild, just to match the changes, especially for query socket timeout set and recovery.
> 
> I just found some new bug and push a new commit now, we may have new bug and issue with it, anyway, we can continue improve it and try to make it stable.

I think tests will help us identify those bugs. Right now, with all those changes I still don't fully understand that and if this will fix it.

**Review by rokam — APPROVED** [review]

**Comment by wuwentao** [comment]
@rokam  thanks, but we can only add unit test, it's not real device func test.... this is the key point.
all the unit tes only can test our code logic, and it can't test any device func, all of our unit test should design to test the code logic......
so I just think we can quickly release it and check/confirm it with real device func, then we can found the result.

anyway, we just need to publish a new release with the socket error bug, we have known this bug for too many weeks and pending the fix for a long time now. and please don't worry, I can confirm I can add some unit test later, this version should not a finally or stable version, it still have more step and process need to improve.

In a company DEV release process, they should have all the device/product to run real device func test, but we don't have all the devices.....
so I just can use all of my local device to test the logic and basic func, also refer to the old logic, then publish a release to double check with our user's device, got new bug/issue and fix it, improve it.

**Comment by wuwentao** [comment]
@rokam push a new commit again.
fix: when refresh_status, socket exist, and set query timeout to 2, send query to device and  recv msg, in recv_msg got socket exception, it will close socket and trigger reconnect.
so recovery socket timeout should be skip/disable when timeout/exception exist, and continue to run the reconnect job....

in this step, I think we can only do connect and no need to probe protocol in future, but no plan to change it in current MR....
as it also required more time to test and verify it.

**Review by rokam — APPROVED** [review]

**Comment by wuwentao** [comment]
@rokam thanks, could you help to publish a new release for midea-local?

**Pull request merged**
