### PR TITLE
fix: tank is always seen as full

### PR DESCRIPTION
**Pull request by chemelli74**
## Summary by CodeRabbit

- **New Features**
	- Enhanced the tank fullness calculation for better reliability and clarity in device management.
	- Introduced debug logging to provide insights into the tank's status.
  
- **Bug Fixes**
	- Improved the logic for updating the tank's fullness attribute to ensure accuracy based on the latest data.

### CODE REVIEW

**Comment by Vetti52** [comment]
Tank_full is now working as expected.

**Comment by chemelli74** [comment]
> Tank_full is now working as expected.

As discussed via Discord, waiting for your last test before merging.

**Comment by Vetti52** [comment]
Currently I could confirm, that the status changed to „problem“, when the tank was completely filled, and/or when removed. And after inserting the empty tank again, the status changed to „ok“. So, it works as expected now.

**Review by rokam — APPROVED** [review]
LGTM

**Pull request merged**
