### PR TITLE
fix: ed device power/lock return message set and body_type 0x15 parse

### LINKED ISSUE #283: colmo DA01 powe/lock action got unidentified protocol
### HA core version

_No response_

### Current integration version

0.5.7

### Last known working integration version

not know

### Device type and model

Water Drinking Appliance 63200860 (895)

### Working mobile app

Meiju

### The description of problem

there is a colmo DA01 device, in default query mode, it works well.

once we click power/lock button, it will received a unidentified protocol.

after check and debug with the packet, the content is the same content as query, and only body_type/message_type is different.

based on midea device protocol, message_type 0x02 should be set packet and used to send it to device, seems this device just response it and homeassistant received this packet.

in first step, we can simple parse it and update the status as query message
in the future step, we can continue check and confirm the power/lock action, as these action may not works for colmo DA01 device.

### 'message type': '.04'
```
ff010700400010050201100602400103010103101c05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121c08121f09121f3a4000000000
```

**'message type': '.02':**
```
15020700400010050201100602400103010103101c05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121c08121f09121f3a4000000000
```
only the first two data is difference.

### Solution:
response message parse message_type 02 and body_type  15

### **log** 

```
2024-08-29 18:38:56.749 DEBUG (管线机) [midealocal.device] [210006727698088] Status update: {'power': False, 'water_consumption': 7.088, 'child_lock': True}
2024-08-29 18:38:57.731 DEBUG (管线机) [midealocal.devices.ed] [210006727698088] Received: {'header': 'aa89ed00000000000004', 'body': 'ff010700400010050201100602400103010103101c05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121c08121e09121f3a4000000000', 'message type': '.04', 'body type': '.ff'}
2024-08-29 18:38:57.732 DEBUG (管线机) [midealocal.device] [210006727698088] Status update: {'power': False, 'water_consumption': 7.088, 'child_lock': True}
2024-08-29 18:38:58.711 DEBUG (SyncWorker_5) [midealocal.device] [210006727698088] Sending: {'header': 'aa0ded00000000000002', 'body': '150100', 'message type': '.02', 'body type': '.15'}
2024-08-29 18:38:58.745 DEBUG (管线机) [midealocal.devices.ed] [210006727698088] Received: {'header': 'aa89ed00000000000004', 'body': 'ff010700400010050201100602400103010103101c05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121c08121f09121f3a4000000000', 'message type': '.04', 'body type': '.ff'}
2024-08-29 18:38:58.746 DEBUG (管线机) [midealocal.device] [210006727698088] Status update: {'power': False, 'water_consumption': 7.088, 'child_lock': True}
2024-08-29 18:38:58.960 DEBUG (管线机) [midealocal.devices.ed] [210006727698088] Received: {'header': 'aa89ed00000000000002', 'body': '15020700400010050201100602400103010103101c05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121c08121f09121f3a4000000000', 'message type': '.02', 'body type': '.15'}
2024-08-29 18:38:58.960 DEBUG (管线机) [midealocal.device] [210006727698088] Unidentified protocol
2024-08-29 18:38:59.735 DEBUG (管线机) [midealocal.devices.ed] [210006727698088] Received: {'header': 'aa89ed00000000000004', 'body': 'ff010700400010050201100602400103010103101c05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121c08121f09121f3a4000000000', 'message type': '.04', 'body type': '.ff'}
2024-08-29 18:38:59.736 DEBUG (管线机) [midealocal.device] [210006727698088] Status update: {'power': False, 'water_consumption': 7.088, 'child_lock': True}
2024-08-29 18:39:01.044 DEBUG (SyncWorker_12) [midealocal.device] [210006727698088] Sending: {'header': 'aa0ded00000000000002', 'body': '150100', 'message type': '.02', 'body type': '.15'}
2024-08-29 18:39:01.270 DEBUG (管线机) [midealocal.devices.ed] [210006727698088] Received: {'header': 'aa89ed00000000000002', 'body': '15020700400010050201100602400103010103101c05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121c08121f09121f3a4000000000', 'message type': '.02', 'body type': '.15'}
2024-08-29 18:39:01.271 DEBUG (管线机) [midealocal.device] [210006727698088] Unidentified protocol
2024-08-29 18:39:01.727 DEBUG (管线机) [midealocal.devices.ed] [210006727698088] Received: {'header': 'aa89ed00000000000004', 'body': 'ff010700400010050201100602400103010103101d05103706102d0b10531150b01b00000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d40007121d08121f09121f3a4000000000', 'message type': '.04', 'body type': '.ff'}
``` 
[https://api.github.com/repos/wuwentao/midea_ac_lan/issues/299]

### PR DESCRIPTION
**Pull request by wuwentao**
fix #283 
origin from https://github.com/wuwentao/midea_ac_lan/issues/299

## Summary by CodeRabbit

- **New Features**
	- Introduced a new body type, `X15`, to enhance message categorization.
	- Expanded response handling to accommodate a new message type, improving flexibility in message processing.

- **Improvements**
	- Updated initialization parameters for message handling classes to enhance readability and maintainability.
	- Established a comprehensive suite of unit tests for ED message handling, ensuring robust functionality and correctness.

### CODE REVIEW

**Review by chemelli74 — APPROVED** [review]

**Comment by wuwentao** [comment]
> Can you please add tests

hi rokam,

I don't think it can fix the set action bug and all the set feature still can't works.
it only fix the response. maybe ignore it also can works. as there's still query message exist.

so I don't think I can add test for it now.


in addition, this device is not a standard ED device,like a part of standard ED device and removed most of the core feature in ED device.
still need more info and a physical ED device to confirm current feature can works well. 

as I found more difference from current code and the lua scripts.
I'm not sure with the normal ED device, will do more test and change it in future PR.

**Comment by wuwentao** [comment]
@Necroneco I remember you have changed some translate and can be used for ED device.

what's your device type?

**Comment by Necroneco** [comment]
> @Necroneco I remember you have changed some translate and can be used for ED device.
> 
> what's your device type?

Colmo RA08, I have never used the `power` and `child lock` here.
And I tested the new code here, nothing happened either.

**Comment by wuwentao** [comment]
@Necroneco  thanks, I have a DA01, the power and child lock should not work, it still have error from the lua script.
but current response msg can't be parse, so this PR just fix the response msg and not fix the power/lock issue.
I'm not sure with normal product, so not change it.
maybe can have a try with next PR to change it

**Review by Necroneco — DISMISSED** [review]

**Comment by wuwentao** [comment]
> Can you please add tests

done, please help to check and review

**Review by rokam — APPROVED** [review]

**Pull request merged**
