### PR TITLE
test(a1): first coverage

### PR DESCRIPTION
**Pull request by rokam**
## Summary by CodeRabbit

- **Tests**
  - Added comprehensive unit tests for Midea A1 device functionalities, including initial attributes, modes, fan speeds, water level sets, message processing, query building, and attribute setting.
  - Enhanced message protocol tests for A1 devices, covering message creation, body content validation, and response parsing.

### CODE REVIEW

**Comment by chemelli74** [comment]
I see you use "old "unittest.
Is there a specific reason for that ?

**Comment by rokam** [comment]
To use fixtures, I need disallow_untyped_decorators = false in mypy

**Comment by rokam** [comment]
@chemelli74 do we change mypy or keep using unittest?

**Comment by chemelli74** [comment]
Please change mypy bit right after we merge it.
We should be ready for that.
Just 1 PR needs your blessing

**Review by chemelli74 — APPROVED** [review]
Nice job, thx !

**Pull request merged**
