### PR TITLE
fix: message protocol version default

### PR DESCRIPTION
**Pull request by chemelli74**

### CODE REVIEW

**Review by rokam — APPROVED** [review]

**Review by rokam — DISMISSED** [review]
Still need to change de devices msgs

**Comment by chemelli74** [comment]
> Still need to change de devices msgs

Sorry I lost this part, can you be more detailed ?

**Comment by rokam** [comment]
> > Still need to change de devices msgs
> 
> Sorry I lost this part, can you be more detailed ?

Look that  CI is failing. 
``
midealocal/devices/e1/__init__.py:135: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e1/__init__.py:170: error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e1/__init__.py:174: error: Argument 1 to "MessageLock" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e1/__init__.py:178: error: Argument 1 to "MessageStorage" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fc/__init__.py:127: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fc/__init__.py:166: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b8/__init__.py:94: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b8/__init__.py:111: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b8/__init__.py:133: error: Argument 1 to "MessageSetCommand" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e6/__init__.py:74: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e6/__init__.py:95: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b0/__init__.py:77: error: Argument 1 to "MessageQuery01" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b6/__init__.py:84: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b6/__init__.py:121: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b6/__init__.py:125: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b6/__init__.py:130: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b6/__init__.py:133: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b6/__init__.py:137: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b6/__init__.py:144: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ca/__init__.py:90: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e8/__init__.py:79: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x26/__init__.py:123: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x26/__init__.py:153: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/c3/__init__.py:119: error: Argument 1 to "MessageQueryBasic" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/c3/__init__.py:120: error: Argument 1 to "MessageQuerySilence" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/c3/__init__.py:214: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/c3/__init__.py:246: error: Argument 1 to "MessageSetECO" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/c3/__init__.py:252: error: Argument 1 to "MessageSetSilent" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:145: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:278: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:286: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:291: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:296: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:315: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:320: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:323: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fa/__init__.py:330: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ea/__init__.py:174: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ce/__init__.py:106: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ce/__init__.py:131: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
Found 40 errors in 13 files (checked 38 source files)
midealocal/devices/c2/__init__.py:103: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/c2/__init__.py:120: error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/c2/__init__.py:130: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/bf/__init__.py:77: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/dc/__init__.py:65: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/dc/__init__.py:97: error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/dc/__init__.py:101: error: Argument 1 to "MessageStart" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b3/__init__.py:106: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/cc/__init__.py:109: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/cc/__init__.py:156: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fd/__init__.py:128: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fd/__init__.py:162: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/cd/__init__.py:91: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/cd/__init__.py:117: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fb/__init__.py:83: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fb/__init__.py:106: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fb/__init__.py:112: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/fb/__init__.py:123: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ec/__init__.py:186: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/db/__init__.py:65: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/db/__init__.py:98: error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/db/__init__.py:102: error: Argument 1 to "MessageStart" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x13/__init__.py:102: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x13/__init__.py:134: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b4/__init__.py:77: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x34/__init__.py:135: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x34/__init__.py:170: error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x34/__init__.py:174: error: Argument 1 to "MessageLock" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x34/__init__.py:178: error: Argument 1 to "MessageStorage" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/b1/__init__.py:77: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
Found 30 errors in 14 files (checked 38 source files)
midealocal/devices/x40/__init__.py:102: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/x40/__init__.py:136: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/cf/__init__.py:69: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/cf/__init__.py:89: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/cf/__init__.py:101: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/da/__init__.py:91: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/da/__init__.py:179: error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/da/__init__.py:183: error: Argument 1 to "MessageStart" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ed/__init__.py:82: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ed/__init__.py:102: error: Argument 1 to "MessageNewSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ed/__init__.py:104: error: Argument 1 to "MessageOldSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e3/__init__.py:86: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e3/__init__.py:108: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e3/__init__.py:129: error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e3/__init__.py:135: error: Argument 1 to "MessageNewProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:171: error: Argument 1 to "MessageSubProtocolQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:172: error: Argument 1 to "MessageSubProtocolQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:173: error: Argument 1 to "MessageSubProtocolQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:176: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:177: error: Argument 1 to "MessageNewProtocolQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:178: error: Argument 1 to "MessagePowerQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:184: error: Argument 1 to "MessageCapabilitiesQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:185: error: Argument 1 to "MessageCapabilitiesQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:235: error: Argument 1 to "MessageGeneralSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:259: error: Argument 1 to "MessageSubProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:308: error: Argument 1 to "MessageToggleDisplay" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:315: error: Argument 1 to "MessageNewProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:320: error: Argument 1 to "MessageNewProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:341: error: Argument 1 to "MessageNewProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:344: error: Argument 1 to "MessageNewProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/ac/__init__.py:352: error: Argument 1 to "MessageNewProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/a1/__init__.py:112: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/a1/__init__.py:162: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e2/__init__.py:116: error: Argument 1 to "MessageQuery" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e2/__init__.py:131: error: Argument 1 to "MessageSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e2/__init__.py:[152](https://github.com/rokam/midea-local/actions/runs/11183424357/job/31091989690?pr=316#step:5:157): error: Argument 1 to "MessagePower" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
midealocal/devices/e2/__init__.py:158: error: Argument 1 to "MessageNewProtocolSet" has incompatible type "int"; expected "ProtocolVersion"  [arg-type]
```

**Comment by chemelli74** [comment]
The protocol compare sound like a wrong logic now that we know we are speaking about message and not device.
I would remove the if completely and see what happens on real life

**Comment by chemelli74** [comment]
> The protocol compare sound like a wrong logic now that we know we are speaking about message and not device. I would remove the if completely and see what happens on real life

See #320

**Review by rokam — APPROVED** [review]
LGTM

**Comment by chemelli74** [comment]
> LGTM, just need to fix the last CI error.

It was auto merged with the error ☺️

We need to fix it

**Pull request merged**
